export const TEXTS = {
  HEADER_TITLE: 'Task Tracker',
  HEADER_ADD_TASK: 'Add task',
  SCREEN_PLANNED: 'Planned',
  SCREEN_IN_PROGRESS: 'In Progress',
  SCREEN_COMPLETED: 'Completed',
  TASK_ESTIMATED: 'Estimated',
  NEW_TASK_NAME: 'Name',
  NEW_TASK_DESCPRIPTION: 'Description',
  NEW_TASK_ESTIMATE: 'Estimate',
  NEW_TASK_TITLE: 'Create a new task',
  NEW_TASK_CREATE: 'Create',
  NEW_TASK_CANCEL: 'Cancel',
  PREV_TASK_GO_BACK: 'Go back',
  NEXT_TASK_IN_PROGRESS: 'Start',
  NEXT_TASK_COMPLETED: 'Finish',
  INFO_MODAL_STATES_TIMES: 'State times',
  DELETE_MODAL_TEXT_PART_1: 'Do you want to delete "',
  DELETE_MODAL_TEXT_PART_2: '" task?',
  DELETE_MODAL_SUBTITLTE: 'This action is no reversible',
  DELETE_MODAL_DELETE: 'Delete'
}